# Generated by Django 6.0.2 on 2026-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other')], default='checking', max_length=255),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=50),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
