# Generated by Django 6.0.2 on 2026-02-22 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_account_type_alter_fileupload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='file_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.fileupload'),
        ),
    ]
