# Generated by Django 6.0.2 on 2026-02-22 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_make_transaction_file_upload_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
