# Generated by Django 6.0.2 on 2026-02-24 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_add_subcategory_to_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'location classifications',
            },
        ),
        migrations.CreateModel(
            name='PersonClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'person classifications',
            },
        ),
        migrations.CreateModel(
            name='TimeClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'time classifications',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.locationclassification'),
        ),
        migrations.CreateModel(
            name='LocationSubClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location_classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_subclassifications', to='budget.locationclassification')),
            ],
            options={
                'verbose_name_plural': 'location subclassifications',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='location_subclassification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.locationsubclassification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='person_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.personclassification'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_classification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='budget.timeclassification'),
        ),
    ]
