# Generated by Django 6.0.2 on 2026-02-24 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_locationclassification_personclassification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='budget.account')),
            ],
            options={
                'ordering': ['-period_end'],
                'constraints': [models.UniqueConstraint(fields=('account', 'period_end'), name='unique_statement_per_period')],
            },
        ),
    ]
