# Generated by Django 6.0.2 on 2026-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit_card', 'Credit Card'), ('investment', 'Investment'), ('loan', 'Loan'), ('other', 'Other'), ('payroll', 'Payroll')], default='checking', max_length=255),
        ),
    ]
